# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
pip install mdutils

Note: you may need to restart the kernel to use updated packages.


In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)


1.24.3


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
vec=np.zeros(10)
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
print("%d bytes" % (vec.size * vec.itemsize))

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
%run python -c "import numpy; numpy.info(numpy.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
vec=np.zeros(10)
vec[4]=1
print(vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
vec=np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
vec=vec[ : :-1]
print(vec)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
mat = np.arange(9).reshape(3, 3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
mat = np.nonzero([1,2,0,0,4,0])
print(mat)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
mat=np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
mat = np.random.random((3,3,3))
print(mat)

[[[0.88295624 0.76223388 0.45133059]
  [0.68253771 0.63177581 0.65966443]
  [0.33257821 0.05929737 0.92784761]]

 [[0.77625543 0.03205902 0.20663274]
  [0.80480899 0.32402014 0.61374174]
  [0.20306267 0.20770206 0.86416163]]

 [[0.38997386 0.92367001 0.68449917]
  [0.96616177 0.846095   0.89336138]
  [0.72454214 0.61349386 0.17728056]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
mat = np.random.random((10,10))
print(mat)
mini = mat.min()
maxi =mat.max()
print(mini, maxi)

[[0.86236894 0.57710472 0.09201326 0.87964443 0.91001889 0.91434312
  0.22067733 0.10890088 0.0284075  0.66655444]
 [0.09838276 0.6863703  0.63528861 0.43702092 0.55640944 0.03985575
  0.8770046  0.0025538  0.38544298 0.15507717]
 [0.55594447 0.92257652 0.98688762 0.9684256  0.36774803 0.81521718
  0.50393959 0.1924914  0.32481622 0.71808766]
 [0.91316927 0.32426655 0.49070758 0.53954226 0.9644214  0.76569381
  0.82185278 0.19855524 0.524864   0.04929514]
 [0.22332025 0.32123916 0.37736832 0.08293165 0.98973983 0.89817768
  0.49787468 0.49701074 0.05768659 0.86045986]
 [0.44932228 0.67610673 0.91777685 0.08710882 0.13699998 0.68682812
  0.13928048 0.01306626 0.07305594 0.39022249]
 [0.55647907 0.8640387  0.16620959 0.81973332 0.54868905 0.314187
  0.43845053 0.43228786 0.61229702 0.45757403]
 [0.61537279 0.46280861 0.96517843 0.08898554 0.36387366 0.56806492
  0.25795451 0.31433478 0.46052142 0.17132929]
 [0.14696618 0.53776758 0.80896732 0.95761167 0.92225407 0.68108763
  0.82585075 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
vec=np.random.random(30)
print(vec)
vec_mean=vec.mean()
print(vec_mean)

[0.97493046 0.00370457 0.81254685 0.31944675 0.29164053 0.52333245
 0.40701486 0.88288508 0.73136394 0.782813   0.25487968 0.94719642
 0.28996136 0.26449321 0.12247309 0.61450433 0.13556616 0.15077886
 0.72010351 0.54151296 0.60160535 0.08096896 0.4626813  0.01359154
 0.55332322 0.18354717 0.32359446 0.5493862  0.35076775 0.84396246]
0.4578192163594366


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
mat = np.ones((10,10))
mat[1:-1,1:-1] = 0
print(mat)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
mat[:, [0, -1]] = 0
mat[[0, -1], :] = 0
print(mat)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
mat = np.zeros((8,8))
mat[1::2,::2] = 1
mat[::2,1::2] = 1
print(mat)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [22]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
mat = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
mat = np.random.random((5,5))
mat = (mat - np.mean (mat)) / (np.std (mat))
print(mat)

[[ 0.86623683  0.14149678 -0.33221055 -1.70971749  0.15622723]
 [-1.84686442  0.37373512  0.99229525  1.39669023  1.07505688]
 [ 0.01355705  1.15137315  0.87609355 -1.0014325   0.34169681]
 [ 0.03578409  0.02851567  0.84300338 -1.58609145 -1.6028417 ]
 [ 0.366387   -1.19307092  0.15444783 -0.96020378  1.41983597]]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
mat = np.dot(np.arange(15).reshape(5,3),np.arange(6).reshape(3,2))
print(mat)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z=5
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

3125
16
False
5j
5.0
False


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [29]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/3v/51pxc18x3zj639s1qjnhqz8w0000gp/T/ipykernel_3396/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [30]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [31]:
mat = np.zeros((5,5))
mat += np.arange(5)
print(mat)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [32]:
vec = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

5


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [33]:
vec = np.random.random(10)
print(vec)
vec.sort()
print(vec)

[0.46548695 0.29853674 0.74465685 0.3379688  0.73131009 0.29391228
 0.35831279 0.21374129 0.49044692 0.43926963]
[0.21374129 0.29391228 0.29853674 0.3379688  0.35831279 0.43926963
 0.46548695 0.49044692 0.73131009 0.74465685]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [34]:
vec = np.arange(10)
np.add.reduce(vec)

45

#### 43. Make an array immutable (read-only) (★★☆)

In [35]:
arr = np.zeros(10)
arr.flags.writeable = False


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [36]:
vec = np.random.random(10)
print(vec)
print(vec.max())
vec[vec.argmax()] = 0
print(Z)

[0.74654329 0.89791121 0.98979674 0.55673062 0.937342   0.4361455
 0.54483453 0.30741495 0.00465565 0.59655074]
0.9897967423546051
5


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [37]:
vec = np.zeros((5,5), [('x',float),('y',float)])
vec['x'], vec['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(vec)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 49. How to print all the values of an array? (★★☆)

In [38]:
np.set_printoptions(threshold=float("inf"))
vec = np.zeros((40,40))
print(vec)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [39]:
vec = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(vec):
    print(index, value)
for index in np.ndindex(vec.shape):
    print(index, vec[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [40]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [41]:
vec1 = np.random.rand(5, 10)

vec2 = vec1 - vec1.mean(axis=1, keepdims=True)

vec2 = vec1 - vec1.mean(axis=1).reshape(-1, 1)

print(vec2)

[[ 0.27441832 -0.4023701   0.0177925   0.0349248   0.11775693 -0.41136048
   0.28269544  0.39544467 -0.16245191 -0.14685019]
 [ 0.28138484  0.45879256  0.09255604 -0.27087408 -0.22953539 -0.35274575
   0.24532961 -0.25217361  0.27867448 -0.25140871]
 [-0.03803366  0.32524974 -0.24806229 -0.01665122  0.02115181 -0.35428142
   0.21962382 -0.0882836   0.23710271 -0.05781589]
 [-0.03522748 -0.17978044 -0.30112287  0.40470438 -0.25182598 -0.21560997
   0.41436542 -0.26636867 -0.10704976  0.53791535]
 [ 0.6303005  -0.18790532 -0.16058014  0.45133126  0.03154256 -0.2962111
  -0.25524197  0.43400453 -0.33080988 -0.31643043]]


#### 59. How to sort an array by the nth column? (★★☆)

In [42]:
vec = np.random.randint(0,10,(3,3))
print(vec)
print(Z[Z[:,1].argsort()])

[[1 3 6]
 [0 9 2]
 [6 0 9]]
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [43]:
vec=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(vec).all(axis=0))

[False False  True]


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [44]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [45]:
vec = np.ones(10)
vec1 = np.random.randint(0,len(Z),20)
vec += np.bincount(vec1, minlength=len(vec))
print(vec)

[2. 3. 5. 2. 4. 4. 2. 3. 3. 2.]


#### 72. How to swap two rows of an array? (★★★)

In [46]:
arr = np.arange(25).reshape(5,5)
arr[[0,1]] = arr[[1,0]]
print(arr)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 82. Compute a matrix rank (★★★)

In [47]:
mat = np.random.uniform(0,1,(10,10))
m1, m2,m3  = np.linalg.svd(mat)
rank = np.sum(m2 > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [48]:
arr = np.random.randint(0,10,50)
print(np.bincount(arr).argmax())

7


#### 89. How to get the n largest values of an array (★★★)

In [49]:
arr = np.arange(10000)
np.random.shuffle(arr)
n = 5

# Slow
print (arr[np.argsort(arr)[-n:]])

[9995 9996 9997 9998 9999]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [50]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)      
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B) 
np.einsum('i,j->ij', A, B)

array([[0.17681724, 0.12722186, 0.1819815 , 0.2265177 , 0.03701705,
        0.09510531, 0.1105087 , 0.02557081, 0.04587474, 0.07301015],
       [0.14222502, 0.1023324 , 0.14637895, 0.18220216, 0.0297751 ,
        0.07649907, 0.08888897, 0.02056818, 0.03689988, 0.05872657],
       [0.24352692, 0.17522018, 0.25063955, 0.31197839, 0.05098286,
        0.13098668, 0.15220147, 0.03521818, 0.06318238, 0.10055545],
       [0.01614978, 0.01161993, 0.01662146, 0.02068922, 0.00338099,
        0.00868654, 0.01009342, 0.00233554, 0.00419001, 0.00666845],
       [0.2755676 , 0.19827379, 0.28361604, 0.35302518, 0.05769064,
        0.14822052, 0.17222652, 0.03985181, 0.07149525, 0.11378547],
       [0.37411097, 0.26917678, 0.38503754, 0.47926749, 0.07832089,
        0.20122439, 0.23381497, 0.05410287, 0.09706205, 0.15447532],
       [0.07095085, 0.05104988, 0.07302309, 0.09089398, 0.0148537 ,
        0.03816258, 0.04434345, 0.01026071, 0.018408  , 0.02929653],
       [0.05561184, 0.04001331, 0.0572360